### PR TITLE
2.3.2 beta

### PR DESCRIPTION
**Pull request by rullzer**
Windows binary at: https://download.nextcloud.com/desktop/prereleases/Windows/Nextcloud-2.3.2.1beta-setup.exe

OSX package at:
https://download.nextcloud.com/desktop/prereleases/Mac/Nextcloud-2.3.2.1beta.pkg

TODO:

Build:
- [x] Windows
- [x] OS X
- [ ] Check automatically build packages
- [ ] Once all done merge and tag

### CODE REVIEW

**Comment by rullzer** [comment]
@mario can you build the OSX beta?

**Comment by rullzer** [comment]
@ivaradi @probonopd could you check the automated builds if all is going OK there?

**Comment by mario** [comment]
@rullzer sure, I can try :)

**Comment by mario** [comment]
Done.

**Comment by probonopd** [comment]
@rullzer AppImage build seems to be working, at least it still and uploads output https://travis-ci.org/nextcloud/client_theming/jobs/234736677#L2114.

**Comment by rullzer** [comment]
Ok 1 seems to fail. But that is likely because it takes the wrong base image because i did not tag yet... so lets merge and tag...

**Review by LukasReschke — APPROVED** [review]

**Pull request merged**
