### PR TITLE
snap: deploy to the store

### PR DESCRIPTION
**Pull request by 3v1n0**
This allows to automatically deploy on ubuntu store.
Macaron can only be decrypted using the snapcraft keys defined in travis.

### CODE REVIEW

**Review by kyrofa — APPROVED** [review]
I tested this on a project branch, seems to work great.

**Comment by 3v1n0** [comment]
Looks good, I think we can go with this!

**Comment by oparoz** [comment]
Just asked @rullzer to review this to make sure all is good on his side.

**Comment by kyrofa** [comment]
@rullzer quick ping here. Should be an easy review.

**Comment by rullzer** [comment]
Uhm... well. I'm fine. Just  as long as it is clear that I/We won't do support on this.

**Comment by kyrofa** [comment]
You're welcome to ping @3v1n0 or myself on snap-specific issues.

**Comment by kyrofa** [comment]
I'll go ahead and merge this, then.

**Pull request merged**
