### PR TITLE
Fix AppImage builds on Travis CI

### PR DESCRIPTION
**Pull request by probonopd**
This should fix the AppImage builds on Travis CI by reverting to Qt 4.

### CODE REVIEW

**Comment by probonopd** [comment]
The bundled Qt is not optimized for size yet, likely some of the Qt plugins can be removed (which?).

**Comment by probonopd** [comment]
@rullzer or @enoch85 please review and merge this, it would fix the continuous builds.

**Review by enoch85 — APPROVED** [review]

**Comment by probonopd** [comment]
Thanks @enoch85. An AppImage is now being generated, the transfer.sh download URL can be seen toward the end of the [Travis CI build log](https://travis-ci.org/nextcloud/client_theming).

**Comment by enoch85** [comment]
@probonopd Stil some failures with QT5 when Travis runs build.sh. Would that be possible to fix?

**Comment by probonopd** [comment]
I had reverted from Qt 5 to Qt 4 because this application apparently has still issues with Qt 5.

**Pull request merged**
