### PR TITLE
Bump client to 2.3.0-beta1

### PR DESCRIPTION
**Pull request by rullzer**
This will be the new master once the 2.3 is out.

@LukasReschke can I ask you to build OSX stuff

@ivaradi and @probonopd if you want/can maybe we can build the beta also for Fedora/debian? Else you can already play with this for the final.

### CODE REVIEW

**Comment by probonopd** [comment]
> @probonopd if you want/can maybe we can build the beta also for Fedora/debian? 

The AppImage build should also work for Fedora and debian. Please let me know if you think it doesn't.

**Comment by enoch85** [comment]
2.3.0 is released. Can we merge this now?

**Comment by enoch85** [comment]
@rullzer Btw, shoulnd't this be 2.3.0 stable and not 2.3.0 beta?

**Comment by probonopd** [comment]
The Travis CI build script [falls down](https://travis-ci.org/nextcloud/client_theming/builds/201806221) on this one - have the build dependencies changed?

**Comment by rullzer** [comment]
@enoch85 no I'll create one for the rc soon

**Comment by rullzer** [comment]
@probonopd not as far as I know. Which qt are you building against?

**Comment by probonopd** [comment]
Qt 4

**Pull request merged**
