### PR TITLE
make if more obvious where to report issues

### PR DESCRIPTION
**Pull request by enoch85**
cc @rullzer @ivaradi

### CODE REVIEW

**Comment by enoch85** [comment]
Ping @ivaradi @rullzer Can we merge this please?

**Review by michaelstingl — CHANGES_REQUESTED** [review]
Better also report packaging issues here. (maybe build issues too)

**Comment by enoch85** [comment]
@michaelstingl Please see new commit

**Review by michaelstingl — APPROVED** [review]

**Comment by enoch85** [comment]
@michaelstingl Can you please add a review so that I can merge?

**Comment by michaelstingl** [comment]
Looks good to me. Thanks for the change 👍 

make_if_more_obvious_where_to_report_issues_by_enoch85_ _pull_request__176_ _nextcloud_client_theming

**Comment by michaelstingl** [comment]
@enoch85 You need at least one reviewer with write access to this repo. I can't help here.

**Review by juliusknorr — APPROVED** [review]

**Comment by enoch85** [comment]
Thanks @juliushaertl

**Pull request merged**
