### PR TITLE
[RC1] 2.3.0

### LINKED ISSUE #81: owncloud client 2.3.0 source code has fixed issues with unity-panel-service memory leak and CPU usage
FYI
please update relevant nextcloud code.

### PR DESCRIPTION
**Pull request by rullzer**
This will become the official 2.3.0

I'll build the windows packages soon and hopefully OS X will follow shortly.

Fixes #81

### CODE REVIEW

**Comment by enoch85** [comment]
Quick question, why use the RC release and not the final stable release? Or are those releases the same, commit-wise?

**Comment by rullzer** [comment]
@enoch85 we just want to make sure it all is tested. If nothing breaks they will be the same. This is the final code of upstream. Just now we also have time to build the OS X client etc.

**Review by enoch85 — APPROVED** [review]

**Comment by enoch85** [comment]
@rullzer OK to merge or is anything left to do here?

**Comment by rullzer** [comment]
Lets merge. And soon build a final ;)

**Pull request merged**
