### PR TITLE
add launchpad

### PR DESCRIPTION
**Pull request by enoch85**

### CODE REVIEW

**Comment by enoch85** [comment]
cc @rullzer Made this PR to check what failed. You assumption about a tag was wrong. How do we fix this?

cc @ivaradi

**Comment by ivaradi** [comment]
There are two issues:

- The logic determining the latest version number (which should be 2.3.2) does not work correctly, hence the script wants to use the base source package for 2.3.1. I know what the problem is, and will be able to fix and test it in the evening. I would also like to add a check for the version tag being for a beta version, in which case the upload to Launchpad would not happen (or would go into some beta PPA later on).

- One of the patches that are needed for 2.3.1 does not seem to be necessary anymore thus its application fails. Perhaps the other patch needs to be modified as well.

**Comment by rullzer** [comment]
@ivaradi thanks a lot!

**Comment by ivaradi** [comment]
I think it should be OK now.

**Comment by enoch85** [comment]
@rullzer Checks are OK, can you review squash and merge please?

**Review by ivaradi — APPROVED** [review]

**Comment by enoch85** [comment]
Thanks @ivaradi

**Comment by enoch85** [comment]
@ivaradi 

```
The command "linux/travis-build.sh script" exited with 0.
after_success
0.01s$ linux/travis-build.sh after_success
+TRAVIS_BUILD_STEP=after_success
+DOCKER_BUILDER_NAME=builder
++dirname linux/travis-build.sh
+THIS_PATH=linux
+'[' -z after_success ']'
+'[' debian == appimage ']'
+'[' debian == snap ']'
+'[' debian == debian ']'
+linux/debian/travis-build.sh after_success
+shopt -s extglob
+TRAVIS_BUILD_STEP=after_success
+PPA=ppa:nextcloud-devs/client
+PPA_BETA=ppa:nextcloud-devs/client-beta
+OBS_PROJECT=home:ivaradi
+OBS_PACKAGE=nextcloud-client
+OBS_PACKAGE_BETA=nextcloud-client-beta
+OBS_SUBDIR=home:ivaradi/nextcloud-client
+'[' after_success == install ']'
+'[' after_success == script ']'
+'[' after_success == snap_store_deploy ']'
dpl.0
Fetching: dpl-1.8.32.gem (100%)
Successfully installed dpl-1.8.32
1 gem installed
dpl.1
Installing deploy dependencies
!!! Script support is experimental !!!
dpl.2
Preparing deploy
dpl.3
Deploying application
+TRAVIS_BUILD_STEP=snap_store_deploy
+DOCKER_BUILDER_NAME=builder
++dirname linux/travis-build.sh
+THIS_PATH=linux
+'[' -z snap_store_deploy ']'
+'[' debian == appimage ']'
+'[' debian == snap ']'
+'[' debian == debian ']'
+linux/debian/travis-build.sh snap_store_deploy
+shopt -s extglob
+TRAVIS_BUILD_STEP=snap_store_deploy
+PPA=ppa:nextcloud-devs/client
+PPA_BETA=ppa:nextcloud-devs/client-beta
+OBS_PROJECT=home:ivaradi
+OBS_PACKAGE=nextcloud-client
+OBS_PACKAGE_BETA=nextcloud-client-beta
+OBS_SUBDIR=home:ivaradi/nextcloud-client
+'[' snap_store_deploy == install ']'
+'[' snap_store_deploy == script ']'
+'[' snap_store_deploy == snap_store_deploy ']'
+cd ..
++cat kind
+kind=beta
+echo 'kind: beta'
kind: beta
+test beta = beta
+PPA=ppa:nextcloud-devs/client-beta
+OBS_PACKAGE=nextcloud-client-beta
+test [secure] -a [secure]
+for changes in 'nextcloud-client_*~+([a-z])1_source.changes'
+dput ppa:nextcloud-devs/client-beta nextcloud-client_2.3.2-20170524.152636~trusty1_source.changes
gpg: Signature made Wed 24 May 2017 04:35:37 PM UTC using RSA key ID 7D14AA7B
gpg: Good signature from "Nextcloud Developers (This key is to be used in automation scripts by Nextcloud) <ivaradi@varadiistvan.hu>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 84B6 DCB8 01B4 1504 2F78  0E95 2265 D876 7D14 AA7B
gpg: Signature made Wed 24 May 2017 04:35:36 PM UTC using RSA key ID 7D14AA7B
gpg: Good signature from "Nextcloud Developers (This key is to be used in automation scripts by Nextcloud) <ivaradi@varadiistvan.hu>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 84B6 DCB8 01B4 1504 2F78  0E95 2265 D876 7D14 AA7B
+for changes in 'nextcloud-client_*~+([a-z])1_source.changes'
+dput ppa:nextcloud-devs/client-beta nextcloud-client_2.3.2-20170524.152636~xenial1_source.changes
gpg: Signature made Wed 24 May 2017 04:35:58 PM UTC using RSA key ID 7D14AA7B
gpg: Good signature from "Nextcloud Developers (This key is to be used in automation scripts by Nextcloud) <ivaradi@varadiistvan.hu>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 84B6 DCB8 01B4 1504 2F78  0E95 2265 D876 7D14 AA7B
gpg: Signature made Wed 24 May 2017 04:35:58 PM UTC using RSA key ID 7D14AA7B
gpg: Good signature from "Nextcloud Developers (This key is to be used in automation scripts by Nextcloud) <ivaradi@varadiistvan.hu>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 84B6 DCB8 01B4 1504 2F78  0E95 2265 D876 7D14 AA7B
+for changes in 'nextcloud-client_*~+([a-z])1_source.changes'
+dput ppa:nextcloud-devs/client-beta nextcloud-client_2.3.2-20170524.152636~yakkety1_source.changes
gpg: Signature made Wed 24 May 2017 04:36:22 PM UTC using RSA key ID 7D14AA7B
gpg: Good signature from "Nextcloud Developers (This key is to be used in automation scripts by Nextcloud) <ivaradi@varadiistvan.hu>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 84B6 DCB8 01B4 1504 2F78  0E95 2265 D876 7D14 AA7B
gpg: Signature made Wed 24 May 2017 04:36:22 PM UTC using RSA key ID 7D14AA7B
gpg: Good signature from "Nextcloud Developers (This key is to be used in automation scripts by Nextcloud) <ivaradi@varadiistvan.hu>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 84B6 DCB8 01B4 1504 2F78  0E95 2265 D876 7D14 AA7B
+for changes in 'nextcloud-client_*~+([a-z])1_source.changes'
+dput ppa:nextcloud-devs/client-beta nextcloud-client_2.3.2-20170524.152636~zesty1_source.changes
gpg: Signature made Wed 24 May 2017 04:36:44 PM UTC using RSA key ID 7D14AA7B
gpg: Good signature from "Nextcloud Developers (This key is to be used in automation scripts by Nextcloud) <ivaradi@varadiistvan.hu>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 84B6 DCB8 01B4 1504 2F78  0E95 2265 D876 7D14 AA7B
gpg: Signature made Wed 24 May 2017 04:36:44 PM UTC using RSA key ID 7D14AA7B
gpg: Good signature from "Nextcloud Developers (This key is to be used in automation scripts by Nextcloud) <ivaradi@varadiistvan.hu>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 84B6 DCB8 01B4 1504 2F78  0E95 2265 D876 7D14 AA7B
+mkdir osc
+cd osc
+osc co home:ivaradi nextcloud-client-beta
A    home:ivaradi
A    home:ivaradi/nextcloud-client-beta
At revision None.
+osc delete 'home:ivaradi/nextcloud-client/*'
Error: "/home/travis/build/nextcloud/osc/home:ivaradi/nextcloud-client" is not an osc package working copy.
Script failed with status 1
failed to deploy
```

Don't know if it's Travis or it's something else?

**Comment by ivaradi** [comment]
I set up a beta package in the OpenSuSE Build System for the Debian packages, and modified the script to  upload beta versions there. However, I forgot to change one of the environment variables, so this part failed.

Deployment is not run for pull requests, which is a good thing, but unfortunately it resulted in this part remaining untested.

I am just about to commit the fix.

The good news is that the Ubuntu packages have been built in the beta PPA. Maybe I am going to add the info into the README.

**Comment by enoch85** [comment]
> The good news is that the Ubuntu packages have been built in the beta PPA. Maybe I am going to add the info into the README.

Please do. Thanks!

**Pull request merged**
