### PR TITLE
Fix mac build instructions

### PR DESCRIPTION
**Pull request by mario**
Signed-off-by: Mario Danic <mario@lovelyhq.com>

### CODE REVIEW

**Comment by mario** [comment]
@rullzer can I get this merged pls? :P

**Comment by mario** [comment]
Do not merge yet, needs updates for the client.

**Comment by mario** [comment]
@rullzer this works, and is considered DONE DONE DONE! :)

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Pull request merged**
