### PR TITLE
travis: build snaps at every commit

### PR DESCRIPTION
**Pull request by 3v1n0**
Generated snaps will be saved on transfer.sh for temporary testing, and this supports
uploading to edge store channel once the snapcraft credentials will be generated.

### CODE REVIEW

**Comment by 3v1n0** [comment]
@oparoz this is generating snaps automatically...

If you want jump in in this PR with proper keys and `snapcraft.cfg.in` you should use `snapcraft enable-ci travis` (without pushing the changes it does to `.travis.yaml`, but setting the `SNAPCRAFT_CONFIG_KEY` and `SNAPCRAFT_CONFIG_IV` accordingly).

**Comment by 3v1n0** [comment]
@kyrofa here's the 2nd part...

**Comment by probonopd** [comment]
Thanks @3v1n0 for fixing the [AppImage](http://appimage.org/) builds along the way :-)
Those also get built and uploaded to transfer.sh on each `git push`.

The only problem with this approach is that no one ever sees the them, deeply buried in the Travis CI build logs.

Maybe we should use something like https://github.com/probonopd/uploadtool,

**Comment by 3v1n0** [comment]
@probonopd oh, that's a good option... It's up to @enoch85 to decide, though.

**Comment by enoch85** [comment]
Let's go with the upload tool as suggested.

**Comment by 3v1n0** [comment]
@enoch85 indeed I can do that, but not until you set the `GITHUB_TOKEN` env var in the travis project settings ([see here](https://github.com/probonopd/uploadtool/blob/master/README.md)) so let me know when you've done that and I can proceed with the rest.

**Comment by enoch85** [comment]
> set the GITHUB_TOKEN env var in the travis project settings

cc @oparoz

**Comment by oparoz** [comment]
>>set the GITHUB_TOKEN env var in the travis project settings

>cc @oparoz

@3v1n0 Done

**Comment by 3v1n0** [comment]
Ok, I've finally updated the scripts as per @probonopd suggestion, @oparoz for some reason the travis instance here didn't restart on push, so i wasn't able to test in this PR;

Can you please start it?

**Comment by 3v1n0** [comment]
This works in my fork: https://github.com/3v1n0/nextcloud-client_theming/releases

So, it should do the same here... Now to get the snaps published in the store another action is required at repo-side as said. But you need an ubuntu (docker?) instance and run `snapcraft enable-ci travis` in this repo.

**Comment by 3v1n0** [comment]
The `GITHUB_TOKEN` doesn't seem to be exported i the PR travis instance (for obvious security implications), but I guess it's there for main repo, if you added it to the travis settings...

**Comment by probonopd** [comment]
The `GITHUB_TOKEN` must be set up in the Travis CI settings for the project. PRs don't have access to it and should upload to, e.g., transfer.sh instead, as you have done in your PR. So, looks good to me.

**Review by probonopd — APPROVED** [review]
The uploading part looks good to me but I don't understand anything about the snap portion.

**Comment by enoch85** [comment]
@3v1n0 Is this ready to be merged?

**Comment by 3v1n0** [comment]
@enoch85 speaking about the snap creation and CI check this can be merged.

However if you also want the snap to be uploaded to the Ubuntu store, you need to perform one more step by using `snapcraft` tool in this repo. Get in touch with me for further informations.

We can do that in another branch too, though... So, it's up to you.

**Comment by enoch85** [comment]
Let's get this in now and do another branch for the Ubuntu stuff.

**Comment by 3v1n0** [comment]
Hey @oparoz, any update in getting this uploaded to the ubuntu store?

**Pull request merged**
