### PR TITLE
Debian (Ubuntu) PPA build files

### PR DESCRIPTION
**Pull request by ivaradi**
This patch contains the files I use to build the source package for the PPA and the binary ones for my testing.

### CODE REVIEW

**Comment by enoch85** [comment]
Great! We need reviewers here. ping @LukasReschke @MorrisJobke and others. :)

**Comment by MorrisJobke** [comment]
cc @rullzer

**Comment by enoch85** [comment]
Also, would be great if @ivaradi could get access to this repo so that he can maintain the PPA.

**Comment by rullzer** [comment]
I have no clue about the ubuntu/debian build system. So i can't really judge here. @ivaradi would you be willing to maintain this? If so I could give you access indeed.

**Comment by ivaradi** [comment]
Yes, I would be willing to maintain this.

**Comment by enoch85** [comment]
@rullzer @MorrisJobke What do you say then, merge? I vote yes :+1:

**Review by rullzer — APPROVED** [review]

**Comment by enoch85** [comment]
@ivaradi So, what's the new PPA name so that we can make this official?

**Comment by mightyBroccoli** [comment]
There is this [PPA for Ubuntu](https://launchpad.net/~ivaradi/+archive/ubuntu/nextcloud-client-ppa?field.series_filter=yakkety) but i guess this merge would introduce verions for debian right?

**Comment by enoch85** [comment]
@mightyBroccoli This is the replacement for that PPA.

**Comment by ivaradi** [comment]
@enoch85 The PPA is the one linked by @mightyBroccoli. But what do you mean by "this is the replacement for that PPA"? The PPA contains the binary packages, while this Github repository contains the source files needed to build the source packages from which those binary packages are built by Launchpad. So I don't think the PPA could be replaced. Perhaps only if the packages were accepted into Ubuntu officially.

@mightyBroccoli building packages for Debian and Ubuntu is the same process essentially. However, as far as I know, Launchpad builds only for the various Ubuntu versions, and not for Debian. The Debian packages should be located somewhere else. Maybe I can setup a Debian repository on my server someday.

**Comment by enoch85** [comment]
@ivaradi Ok, then I misunderstood. Couldn't you make it something like `ppa:nextcloud/client` instead?

**Comment by mightyBroccoli** [comment]
@ivaradi basically it is possible to use the ubuntu packages for all debian based os, at least in theory. my debian jessie is not able to run the nextcloud client because debian is not providing libstdc++6 (>= 5.2). Testing would be able to install is with out further configuration jessie not yet. trying the app image now just until jessie is ready to receive greatness :D 
But your idea to set up your own debian repo nevertheless sounds great. I would defiantly use it .

**Comment by ivaradi** [comment]
@mightyBroccoli I have built the packages for jessie using the OpenSUSE build service (as ownCloud does). The sources.list line should be:

`deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_8.0/ /`

Maybe the release key should also be downloaded and installed.

I could not test the client on Debian, but since it compiled, it is likely to work. Please, give it a try, and let me know your results.

**Comment by mightyBroccoli** [comment]
@ivaradi isn't that the owncloud client repository and not the nextcloud variant?

**Comment by ivaradi** [comment]
@mightyBroccoli yes, sorry, I copied the wrong link. The correct line is:

`deb http://download.opensuse.org/repositories/home:/ivaradi//Debian_8.0/ /`

**Comment by ivaradi** [comment]
@enoch85 I have created a team named "nextcloud-devs" on Launchpad. (The "nextcloud" name is already used by for the project producing the Ubuntu snap package, hence the team's name.) The PPA is also created and populated, so its name is  `ppa:nextcloud-devs/client`. 

As "nextcloud-devs" it is a team, I can add anyone from here to be able to update, e.g., the branding or anything or in case I am hit by a tram :)

If it's OK, I will update only this new PPA in the future and will delete the one under my account name after some time.

**Comment by enoch85** [comment]
@ivaradi Great! Make it official in the Nextcloud Forum please. :)

**Comment by enoch85** [comment]
@ivaradi Please also change the code here to the new PPA when the official statement is done.

**Comment by ivaradi** [comment]
@enoch85 I have made the announcement in the forum. The code here does not contain any reference to the PPA being used, I simply manually invoke the `dput` command to upload the source package to the PPA. Is there some automated build being done which could also upload the package?

(That said I do have a pull request waiting with some minor changes, so I would welcome someone reviewing and accepting it :))

**Comment by enoch85** [comment]
@ivaradi You PR is approved. As @rullzer said:

> I have no clue about the ubuntu/debian build system. So i can't really judge here. @ivaradi would you be willing to maintain this? If so I could give you access indeed.

Same goes for me but trust you that the changes are correct. 

Idk about the automated build, but Travis should be able to fix that IMO. @MorrisJobke @kyrofa can maybe answer that better than me...

**Comment by MorrisJobke** [comment]
> Idk about the automated build, but Travis should be able to fix that IMO. @MorrisJobke @kyrofa can maybe answer that better than me...

Sorry to ask: What is the specific question here? We maybe can reuse our drone CI pipeline to build artifacts - they just need to be pushed somewhere, because the drone containers are wiped after execution.

**Comment by kyrofa** [comment]
> Idk about the automated build, but Travis should be able to fix that IMO. @MorrisJobke @kyrofa can maybe answer that better than me...

You can dput the source package from Travis, though you'll of course need to encrypt the key in there for signing it.

**Pull request merged**
