### PR TITLE
Travis build of Ubuntu packages

### PR DESCRIPTION
**Pull request by ivaradi**
The Travis build is extended with producing Ubuntu source packages, which are also deployed to the Ubuntu PPA during deployment.

There are some things to note:

- The changelog is automatically generated from the Git commit log. Only the commits from a certain one are considered. Travis currently clones the repository with a depth of 50, so once we will have more than that many commits, some older entries from the changelog file will be missing. This is not strictly a problem, but is not nice. The solution would be if the script could update the changelog and commit and push the changes back to the repository on the master branch. Is this possible? Is this considered good practice?

- To be able to upload the source packages to the PPA, they must be signed with a GnuPG key. For this purpose I have created a new key pair with the title "Nextcloud Developers". The public key is on the Ubuntu key servers: https://keyserver.ubuntu.com/pks/lookup?op=vindex&fingerprint=on&search=0x2265D8767D14AA7B, while the private one is in the repository in encrypted form in `linux/debian/signing-key.txt.enc`. They key is registered in Launchpad with my account. I wonder if some kind of "functional" user account could be created in Launchpad belonging to a team not a person, though I have not found anything yet.

Feel free to comment on these or any other issues you see with the building process. All suggestions are welcome.

### CODE REVIEW

**Comment by enoch85** [comment]
@3v1n0 does this break the snap build or is it ok?

I'm fine with you having the key @ivaradi, but I agree that a "functional user account" would be better. Though since you maintain this, I see no issues with you having the account yourself.

**Comment by ivaradi** [comment]
One more thing: the "main" version of the package, like 2.3.1 is deduced from the tags matching a regular expression (like "v2.3.1"). So this means that these tags should be properly maintained when new owncloud client releases are made.

**Comment by 3v1n0** [comment]
Snap build is fine, I'd use a better name for the debian script generation though.

**Comment by ivaradi** [comment]
@3v1n0 Which name do you mean exactly? The name of the ` linux/debian/travis-build.sh` script?

**Comment by 3v1n0** [comment]
Yeah... But sorry, I didin't notice it was in the `debian` dir, looks fine then.

**Review by enoch85 — APPROVED** [review]
Based on what @3v1n0 said in this PR.

**Comment by enoch85** [comment]
@ivaradi Build never ends... https://travis-ci.org/nextcloud/client_theming/builds/228599763

**Comment by enoch85** [comment]
Please ignore my previous comment, caching issue on my side.

**Pull request merged**
